package n41msg

type MessageType uint8

const (
	N41_HEARTBEAT_REQUEST              MessageType = 1
	N41_HEARTBEAT_RESPONSE             MessageType = 2
	N41_PFD_MANAGEMENT_REQUEST         MessageType = 3
	N41_PFD_MANAGEMENT_RESPONSE        MessageType = 4
	N41_ASSOCIATION_SETUP_REQUEST      MessageType = 5
	N41_ASSOCIATION_SETUP_RESPONSE     MessageType = 6
	N41_ASSOCIATION_UPDATE_REQUEST     MessageType = 7
	N41_ASSOCIATION_UPDATE_RESPONSE    MessageType = 8
	N41_ASSOCIATION_RELEASE_REQUEST    MessageType = 9
	N41_ASSOCIATION_RELEASE_RESPONSE   MessageType = 10
	N41_VERSION_NOT_SUPPORTED_RESPONSE MessageType = 11
	N41_NODE_REPORT_REQUEST            MessageType = 12
	N41_NODE_REPORT_RESPONSE           MessageType = 13
	N41_SESSION_SET_DELETION_REQUEST   MessageType = 14
	N41_SESSION_SET_DELETION_RESPONSE  MessageType = 15

	N41_SESSION_ESTABLISHMENT_REQUEST  MessageType = 50
	N41_SESSION_ESTABLISHMENT_RESPONSE MessageType = 51
	N41_SESSION_MODIFICATION_REQUEST   MessageType = 52
	N41_SESSION_MODIFICATION_RESPONSE  MessageType = 53
	N41_SESSION_DELETION_REQUEST       MessageType = 54
	N41_SESSION_DELETION_RESPONSE      MessageType = 55
	N41_SESSION_REPORT_REQUEST         MessageType = 56
	N41_SESSION_REPORT_RESPONSE        MessageType = 57
)
